spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pweb-exercicios?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true